package com.example.composechat.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF984713)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffdbc8)
val md_theme_light_onPrimaryContainer = Color(0xFF341100)
val md_theme_light_secondary = Color(0xFF765748)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffdbc8)
val md_theme_light_onSecondaryContainer = Color(0xFF2b160a)
val md_theme_light_tertiary = Color(0xFF646032)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFebe4aa)
val md_theme_light_onTertiaryContainer = Color(0xFF1f1c00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF201a17)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF201a17)
val md_theme_light_surfaceVariant = Color(0xFFf4ded4)
val md_theme_light_onSurfaceVariant = Color(0xFF53443d)
val md_theme_light_outline = Color(0xFF85746c)
val md_theme_light_inverseOnSurface = Color(0xFFfbeee9)
val md_theme_light_inverseSurface = Color(0xFF362f2c)

val md_theme_dark_primary = Color(0xFFffb68e)
val md_theme_dark_onPrimary = Color(0xFF562000)
val md_theme_dark_primaryContainer = Color(0xFF793100)
val md_theme_dark_onPrimaryContainer = Color(0xFFffdbc8)
val md_theme_dark_secondary = Color(0xFFe6beab)
val md_theme_dark_onSecondary = Color(0xFF432b1e)
val md_theme_dark_secondaryContainer = Color(0xFF5c4133)
val md_theme_dark_onSecondaryContainer = Color(0xFFffdbc8)
val md_theme_dark_tertiary = Color(0xFFcec890)
val md_theme_dark_onTertiary = Color(0xFF343107)
val md_theme_dark_tertiaryContainer = Color(0xFF4c481c)
val md_theme_dark_onTertiaryContainer = Color(0xFFebe4aa)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF201a17)
val md_theme_dark_onBackground = Color(0xFFede0db)
val md_theme_dark_surface = Color(0xFF201a17)
val md_theme_dark_onSurface = Color(0xFFede0db)
val md_theme_dark_surfaceVariant = Color(0xFF53443d)
val md_theme_dark_onSurfaceVariant = Color(0xFFd7c2b9)
val md_theme_dark_outline = Color(0xFFa08d84)
val md_theme_dark_inverseOnSurface = Color(0xFF201a17)
val md_theme_dark_inverseSurface = Color(0xFFede0db)

val seed = Color(0xFFa34f1b)
val error = Color(0xFFba1b1b)